"""phase0 amount numeric and tx types

Revision ID: 41d93c5a61bb
Revises: 75d61d028c56
Create Date: 2026-06-03 09:14:49.273111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41d93c5a61bb'
down_revision: Union[str, Sequence[str], None] = '75d61d028c56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'amount',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(precision=40, scale=0),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'amount',
               existing_type=sa.Numeric(precision=40, scale=0),
               type_=sa.BIGINT(),
               existing_nullable=False)
    # ### end Alembic commands ###
